openapi: 3.1.0
info:
  title: Client
  version: '1.0'
  description: Find a client of interest
servers:
  - url: 'http://localhost:3104'
paths:
  /client:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      operationId: get-users-userId
      description: Retrieve clients
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
      parameters:
        - $ref: '#/components/parameters/limit'
  /client/id:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '404':
          $ref: '#/components/responses/404'
        '422':
          $ref: '#/components/responses/500'
        '500':
          $ref: '#/components/responses/500'
      operationId: get-client-id
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/type'
      description: Get a client for supplied parameters
components:
  schemas:
    Client:
      title: Client
      type: object
      description: Find a client of interest
      examples:
        - csid: 123456789
          firstName: Alice
          lastName: Green
          location: Cawongla
          dateOfBirth: 31/01/1970
          csrn: 1236879244
          tfn: 96325874106
          crn: 303458126H
      properties:
        csid:
          type: integer
          description: Unique identifier for the given client.
          format: int32
          minimum: 1
        firstName:
          type: string
        lastName:
          type: string
        location:
          type: string
          description: Postal address town
          format: date
          readOnly: true
        dateOfBirth:
          type: string
          example: '1970-01-31'
          format: date
          readOnly: true
        csrn:
          type: integer
          description: Unique external identifier for the given client.
          default: 0
          format: int32
          minimum: 0
        tfn:
          type: integer
          description: The date that the user was created.
          default: 0
          format: int32
          minimum: 0
        crn:
          type: string
          description: centrelink reference number
          minLength: 11
          maxLength: 11
      required:
        - csid
        - firstName
        - lastName
        - location
        - dateOfBirth
        - csrn
  responses:
    '401':
      description: Example response
      content:
        application/json:
          schema:
            $ref: ../common/error.v1.json
    '404':
      description: 404 response
      content:
        application/json:
          schema:
            $ref: ../common/error.v1.json
    '500':
      description: 500 response
      content:
        application/json:
          schema:
            $ref: ../common/error.v1.json
  parameters:
    limit:
      name: limit
      in: query
      required: true
      schema:
        type: number
        default: 500
        format: int32
        maximum: 1000
      description: limit number returned in query
    id:
      name: id
      in: query
      required: true
      schema:
        type: integer
        format: int32
        minimum: 1
    type:
      name: type
      in: query
      required: true
      schema:
        type: string
        default: CSRN
        enum:
          - CSRN
          - CSID
          - TFN
tags:
  - name: Client
